### ISSUE TITLE
Add documentation regarding CI setup

### ISSUE THREAD

**Issue by dbalatero** [aaronjensen/mergeq#10]
@aaronjensen 

Currently there's no guidance as to what to do on your CI server.

Can you add what a sample CI build step list might look like with `mergeq_ci` in the mix?

**Comment by aaronjensen** [comment]
Added some of this, let me know if it makes sense... It'll probably be helpful to have guides for major online CI platforms, i'm not sure if they're capable of the same constraints that TeamCity is...

**Comment by dbalatero** [comment]
Sounds good. I will likely end up writing a Travis guide, since that's what I'm on right now.
