### ISSUE TITLE
Get a rad animated GIF for the README

### ISSUE THREAD

**Issue by dbalatero** [aaronjensen/mergeq#14]
/cc @aaronjensen 

I think if there were a nice animated gif in the README that illustrated the lifecycle of this tool, it would answer a lot of initial questions for users.

**Comment by dbalatero** [comment]
Know any ~~suckers~~ graphic designers that might be able to help?

**Comment by aaronjensen** [comment]
https://www.pandastrike.com/assets/images/web-surfin-time.gif

**Comment by aaronjensen** [comment]
I'll ask around... unless you think the above one is good enough

**Comment by dbalatero** [comment]
oh duh yeah that works

**Comment by gringocl** [comment]
:+1:

**Comment by aaronjensen** [comment]
well it's not animated, and it's not a gif, but Caleb hooked it up
