### ISSUE TITLE
Do something to avoid having to bundle install twice

### ISSUE THREAD

**Issue by aaronjensen** [aaronjensen/mergeq#3]
We need to bundle install twice at the moment because our script, which needs to run before we bundle install is in a gem... 

Ideas

* generate the ci script into the project's `bin` or `script` folder. we can keep it up to date when merges are queued
* install the gem manually, perhaps by parsing the Gemfile.lock for the appropriate version (yuck)
* deal w/ double bundle install and maybe pipe one to /dev/null

**Comment by dbalatero** [comment]
this seems old

**Comment by aaronjensen** [comment]
we can say it's superseded by #9
