### ISSUE TITLE
Improve installation

### ISSUE THREAD

**Issue by aaronjensen** [aaronjensen/mergeq#9]
Currently this is a gem, but it doesn't use any ruby so it doesn't need to be. Some ideas:

1. Leave it as a gem, but have an installation script that will install it to your project's `bin`. We only need to do this if we want direct access to the shell scripts instead of going through the gem binaries.
1. Add it to homebrew.
1. Provide a curl script and manual instructions, it's only 2 scripts (and one helper file, which could be merged in)

/cc @dbalatero

**Comment by dbalatero** [comment]
How about do option 3 first, then build option 2 using the same script?

**Comment by aaronjensen** [comment]
seems reasonable to me. Nice thing about 3 is the bin get checked into the project, which obviates installing it on each person's machine/the ci machine.

**Comment by dbalatero** [comment]
@aaronjensen starting this on top of #8

**Comment by aaronjensen** [comment]
:+1:
